// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.220531.1

#pragma once
#ifndef WINRT_fnsln_1_H
#define WINRT_fnsln_1_H
#include "winrt/impl/fnsln.0.h"
WINRT_EXPORT namespace winrt::fnsln
{
    struct __declspec(empty_bases) Iexported :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<Iexported>
    {
        Iexported(std::nullptr_t = nullptr) noexcept {}
        Iexported(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
